spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(m1F4wLfCO25trzsGZ67rrDy3/Uei+ngEGd8mmxHKSHQGVE1Ss4FYsc4xsbNbB+3LGDBDwEbAYzVxzsaSiQcOeuUXy0hI14tX+JDhRzkcVPgRpZm4EDaK3/wFosFpjPIYPXmdeptIUBEeADie/Pq3rdiHN0rJiwltKNdynByrqPg=)
    username: ENC(eyxVoViMU+5zTU74sI1tYX5HEBjnGdAHReVBDbm+bxdQKHrm6xKENttwnb4SDM1j)
    password: ENC(fUgDNi/A/Uf40ni+ihb7grUNJVxnNKLvw149K2j9IXZK2j9fsZ5qYRQBb+Gw2DRi)
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    include: secret
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
custom:
  option:
    debug: true
    originLink: "*"
AES:
  secret:
    key: ENC(0T704/UDbXhcXObm18rVRTDbOGD69+/b7rSm26YhiCR9Ax3W+f2gTYdYQA5q5UzgY+kK6La2FbLhdFZ9D76K4wJssbOQM7ZdDci2xvNNeKBzboCT/HpXx3rvcdnfWp71gJLfamlPoGvnXrGCoNMh/tPyPd0OCdGCK81M1xAyEwM=)
jwt:
  secret:
    key: ENC(6G4XOlFMGow3MRX0C+VrLLEakQzy/YXCusF7y0aVWdDIGxYhTk+2maaVyo3urCq2TZWBPYgN6pbAJFg5S/8QZ0LnLlnk567L5QHc/BmNCk3LsG80nT0G5Oa7jYCh72Gx/lynNLYMErCoTDu559JRPwUehvIfdPh8s3qTbVoPexc=)
cloud:
  aws:
    credentials:
      accessKey: ENC(z9aqywsK0B3XPlAheiT+C/PVT56tcZrgI/I0V6pOUKeLU90m/THWdD3cQnpLkDvGougjwqVgpW8u4+ZAi04lVQ==)
      secretKey: ENC(04eF+Z7ygPEiu06gV3jYS7zh21ZJiS0ecdQa7JvQji2yw6D1TKO/rJCxR+TPVb/S+0z0LrqNRqOjaV6rEs1ClUVrdpMUcTNu4Gg1sh0y864=)
    s3:
      bucket: ENC(fnnh/uhVNcgQ4R8aqAkbmYJKJkx/I6B1BnsDoc34bIHYcDIauJNgDgyOqGLfQtkXzVURIkUODNwMkkELziq4sA==)
    region:
      static: ap-northeast-2
    stack:
      auto: false
